### ISSUE TITLE
go install detects @v0.3.3 as @latest

### ISSUE THREAD

**Issue by 97hr** [twitchdev/twitch-cli#116]
Looking at the [tags](https://github.com/twitchdev/twitch-cli/tags), only one is in the "**v**X.X.X" [format recognized by](https://golang.org/ref/mod#versions) `go install`. It looks like the 'v' prefix has come and gone on various [Releases](https://github.com/twitchdev/twitch-cli/releases) as well.

Please consider going back and making the tags consistent one way or the other.

The "[Nightly](https://github.com/twitchdev/twitch-cli/releases/tag/Nightly)" tag (circa Feb) doesn't currently make much sense either.

**Comment by lleadbet** [comment]
I've removed the Nightly tag, and will look to use the `vX.X.X` format going forward; to be clear, we don't explicitly call out support for `go install` however.

**Comment by lleadbet** [comment]
This has been resolved; the newest version `1.1.5` shows up as the latest version
