### ISSUE TITLE
Token command not generating all scopes

### ISSUE THREAD

**Issue by lpcszLewis** [twitchdev/twitch-cli#118]
Im having an issue with the token command.

twitch token -u -s bits:read chat:read chat:edit channel:edit:commercial channel:manage:broadcast channel:read:hype_train                   channel:read:subscriptions moderation:read user:edit user:manage:blocked_users user:read:blocked_users user:read:email user:read:follows user:read:subscriptions user:read:email user:read:follows user:read:subscriptions

When i examine the url generated by twitch-cli it only contains the bits:read scope. Its almost like the parser isnt parsing the whole string. It generates the following url:
id.twitch.tv/oauth2/authorize?client_id=[redacted]&redirect_uri=http%3A%2F%2Flocalhost%3A3000&response_type=code&scope=bits%3Aread&state=[redacted]

![localhost](https://user-images.githubusercontent.com/80648916/139539908-b417efcf-c696-40bf-94e4-b881252e8ca5.png)
Ive attached a screen shot.
regards,
Lewis

**Comment by lleadbet** [comment]
Hi there! You'll need to surround the scopes in quotes such as: 

```
twitch token -u -s "bits:read chat:read chat:edit channel:edit:commercial channel:manage:broadcast channel:read:hype_train channel:read:subscriptions moderation:read user:edit user:manage:blocked_users user:read:blocked_users user:read:email user:read:follows user:read:subscriptions user:read:email user:read:follows user:read:subscriptions"
```

Since most command lines don't accept an array via space separation. Instead, it perceives the additional scopes as arguments to the command. As a result- not really a bug, but something we can explore documenting a little clearer.
