### ISSUE TITLE
Calling bottle :unneeded is deprecated!

### ISSUE THREAD

**Issue by bkash775** [twitchdev/twitch-cli#121]
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the twitchdev/twitch tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/twitchdev/homebrew-twitch/Formula/twitch-cli.rb:10

**Comment by lleadbet** [comment]
This should be resolved in the next release; will close as that's planned for today.
