### ISSUE TITLE
Allow for custom subscription id in verify-subscription command

### ISSUE THREAD

**Issue by Brendonovich** [twitchdev/twitch-cli#123]
`twitch event verify-subscription` currently does not allow a subscription id to be passed with `-i`, unlike most other event commands.

I don't imagine this would be used much, but it would be useful for me as I use the verification request to inform my application that the subscription exists, and update the database as such. Being able to specify an id for the subscription being verified would make my testing more robust, since I would not have to manually edit the database to confirm that the subscription has been verified, instead the webhook handler can perform the update as it usually would.

**Comment by Xemdo** [comment]
Added with #185
