### ISSUE TITLE
Fix tarbomb.

### ISSUE THREAD

**Issue by exegeteio** [twitchdev/twitch-cli#135]
When extracting the Linux .tgz file from the releases page, it is a [tarbomb](http://www.linfo.org/tarbomb.html).  This can be very detrimental to anyone extracting the application.

> A tarbomb, also sometimes written as tar bomb, is a tarball whose contents appear to explode into the current directory or some other existing directory containing a large number of items when untarred rather than into a new directory created by the tarball specifically for such contents.

**Comment by lleadbet** [comment]
@jackmcguire1 - can you elaborate here? Which version/what is expanding into? Looking into the tarball, it shows:

```sh
-rw-r--r--  0 root   root    11361 Jan 12  2021 LICENSE
-rw-r--r--  0 root   root     2063 Jul 27 17:20 README.md
-rwxr-xr-x  0 root   root 10988504 Dec  8 18:25 twitch
```

after running `tar -tvf twitch-cli_1.1.5_Linux_x86_64.tar.gz`

Which matches with what I expect.

**Comment by exegeteio** [comment]
The issue is that the tarball extracts into the current directory without creating a sub directory to extract itself into.

For example, if I'm working in a directory with a preexisting README.md and I extract your tarball, it will overwrite my README.md with the one from your package, destroying work.

This is, at the very least, bad form in the *nix communities I frequent.
