### ISSUE TITLE
Malwarebytes is detecting spyware in the latest release but not the previous one

### ISSUE THREAD

**Issue by JavaScript-aka-Java** [twitchdev/twitch-cli#142]
Scanning the twitch-cli_1.1.5_Windows_x86_64.zip (or installing via scoop) Malwarebytes detects the latest v1.1.5 release as Spyware.PasswordStealer. Same file for release v1.1.3 has no detections.

Here are the results from VirusTotal - https://www.virustotal.com/gui/file/f8d5d5b576b5e4223b810d63d3728ec907a17f50646f4d5c3d816e5289c58ff3/detection

Any idea why?

**Comment by Gary50613** [comment]
same here

**Comment by lleadbet** [comment]
Filed: https://forums.malwarebytes.com/topic/285451-spywarepasswordstealer-false-positive/

**Comment by lleadbet** [comment]
According to them, it should no longer be detecting locally, but is an issue with VirusTotal. Closing, but if you continue to see issues, please @ me.
