### ISSUE TITLE
User token not generated

### ISSUE THREAD

**Issue by shaloonigam** [twitchdev/twitch-cli#143]
After registering my app with a redirect URI of http://localhost:3000, I tried to generate a user token but no response on console.
I am using macOS Big Sur and Google chrome.

Followed the below steps:

1. twitch configure >> added the client id and secret >> Updated configuration.
2. twitch token -u -s “user:read:email”
3. Redirected to app for authorization >> authorized it
4. The browser displays "Feel free to close this browser window." but no response on console, it still shows "Opening browser. Press Ctrl+C to cancel..."
5. On refreshing web browser, I get "This site can’t be reached localhost refused to connect."

How to get the user token? What am I doing wrong?

**Comment by Aberen** [comment]
Getting the same thing, unfortunately, following for fix.

**Comment by Aberen** [comment]
- OS: macOS 11.4
- Browser: Chrome Version 99.0.4844.51
- Installed via homebrew

`$twitch token -u -s "channel:manage:redemptions user:edit:follows"`

Chrome opens up, when I press the 'continue' button. I get greeted with the 'Feel free to close this browser window.' and when I look in the terminal, the user token is blank.

`2022/03/08 10:00:08 User Access Token: [blank]`

Additionally, if I wait a few seconds without pressing 'continue' the terminal dies with the message 'state mismatch'.

**Comment by Aberen** [comment]
Just tried with with one of my other machines. A Windows 10 machine installed via Scoop. Same issue.

**Comment by lleadbet** [comment]
The specific issue is that your redirect is not matching `http://localhost:300` per https://github.com/twitchdev/twitch-cli/blob/main/docs/token.md; it may be nice to expose this to the user, however. 

Will mark this as a feature enhancement as a result.
