### ISSUE TITLE
[Feature request] Select how many pages to auto paginate

### ISSUE THREAD

**Issue by KaMyKaSii** [twitchdev/twitch-cli#152]
For example "-P 10" to get the result of the first 10 pages.

**Comment by Xemdo** [comment]
Which command are you running that needs to be paginated?

**Comment by KaMyKaSii** [comment]
I want to get the 1000 streamers with the most viewers right now. When running "twitch api get streams -q first=100" I get the first 100 as expected, but when running "twitch api get -P streams -q first=100" the last time I ran it I got a result of 113K streams. I would like an option to select the number of times to receive the next page.
