### ISSUE TITLE
[Feature Request] aarch64 build?

### ISSUE THREAD

**Issue by eftSharptooth** [twitchdev/twitch-cli#153]
Any plans to have an aarch64 build for arm linux?

For example 64bit on a rpi4.

**Comment by Xemdo** [comment]
Yeah that should be possible with goreleaser. I'll test this later and if it all works well I'll add it into the next release.

**Comment by eftSharptooth** [comment]
It should be possible, I used your setup to do it locally and it seems to be working fine. Its really just a convenience thing, and I believe supported by goreleaser right away, just have to update the goreleaser to:
    goos:
      - linux
    goarch:
      - amd64
      - arm64

The only reason I ask is it will work on rpi4, and I try to use signed binaries whenever possible. My self-compiled one works, but is not preferable. Thank you! I appreciate the work that has gone into this project!
