### ISSUE TITLE
Erroneous twitch-evensub-subscription-type

### ISSUE THREAD

**Issue by dialogik** [twitchdev/twitch-cli#16]
When receiving mock events, I noticed that all `channel` event types are misspelled in the response headers:

    'twitch-eventsub-subscription-type': 'channels.subscribe'

but shouldn't it be:

    'twitch-eventsub-subscription-type': 'channel.subscribe',

(`channels.<type>` should be `channel.<type>` without the trailing `s` behind `channel`.)

**Comment by lleadbet** [comment]
Hi there! If you run `twitch version`, what is reported?

**Comment by dialogik** [comment]
Yeh sorry, I was using an old version. My bad.

**Comment by lleadbet** [comment]
No worries at all- just making sure! :)
