### ISSUE TITLE
[Feature Request] Add `revocation` EventSub Message Type

### ISSUE THREAD

**Issue by mitchwadair** [twitchdev/twitch-cli#169]
I think it would be useful to be able to test for when an EventSub message is of type `revocation`.  This is the only one currently missing from the three types.

Going off of the current design, it seems like we'd want an additional command like `twitch event revoke <event_type> ...etc`, but it could also be as simple as adding a flag like `-R` and `--revoke` to the `trigger` command.

See [here](https://dev.twitch.tv/docs/eventsub/handling-webhook-events#revoking-your-subscription) for relevant doc

**Comment by mitsuaky** [comment]
It would be very useful for me right now. Looking forward for this feature.
