### ISSUE TITLE
[Feature Request] Add Ability to Set Timestamp in EventSub Commands

### ISSUE THREAD

**Issue by mitchwadair** [twitchdev/twitch-cli#170]
I think it would be useful to be able to test for when an EventSub notification is old/stale.

Not really sure exactly what this would look like.  Maybe a flag on the `trigger` command to set the timestamp some amount of time back, or to set a specific time?

**Comment by Xemdo** [comment]
Just to be clear, are you trying to test this use case from https://dev.twitch.tv/docs/eventsub/handling-webhook-events#processing-an-event:
> Replay attacks
> If you need resiliency against replay attacks, consider the following:
> - Make sure the value of the Twitch-Eventsub-Message-Timestamp request header isn’t older than 10 minutes.
> - Make sure you haven’t seen the ID in the Twitch-Eventsub-Message-Id request header before.

If not, is there another use case I may have missed?

**Comment by mitchwadair** [comment]
Yeah that's the key use case I'd like to test

**Comment by Xemdo** [comment]
Should be added next release

**Comment by mitchwadair** [comment]
Awesome, thanks for getting to that!
