### ISSUE TITLE
bug with post request in version 1.1.7

### ISSUE THREAD

**Issue by vanholler** [twitchdev/twitch-cli#172]
Hello everyone !  I try subscribe to events on my channel , so i user twitch-CLI and try send request with json text, but give trouble on screenshot. Also i try send comand with @path to json , and i gave the same error .  version cli 1.1.7 . 
exemple of my request :
`twitch api post /eventsub/subscriptions -b
`{"type":"user.update","version":"1","condition":{"user_id":"1231231"},
"transport":{"method":"webhook","callback":"http://localhost:3000/webhook/callback",
"secret":"sdfsdfsdfsdfsdfsdf3"}}``
 
but if i use :
twitch api get users -q login=timmi... 
it's all right ) 

also i used ngrok , it is not help me .

error : 
![Screenshot 2022-09-06 210639](https://user-images.githubusercontent.com/32782411/188707697-522f82d6-bebb-4a68-ab1c-303cada7124e.jpg)

i swear , i used different way to resolve this , and send to discord server , nobody could help me .

**Comment by lleadbet** [comment]
@vanholler - Wasn't related to your callback, but instead a bug; #174 fixes this and hoping to roll out shortly (aka next week sometime).

**Comment by vanholler** [comment]
@lleadbet  Thank you so much )
