### ISSUE TITLE
Next expected release/nightly builds available?

### ISSUE THREAD

**Issue by dialogik** [twitchdev/twitch-cli#18]
I have two questions concerning releases:

1. When can the next build be expected?
2. Is there some (official) place to get nightly builds or something like that?

I started setting up Go just for self compiling but ran into quite some issues. And before I bite myself through I just wanted to make sure that there is not already something better available.

**Comment by lleadbet** [comment]
We'll be cutting a release soon, but I did add Nightlies in the interim: https://github.com/twitchdev/twitch-cli/releases/tag/Nightly

**Comment by dialogik** [comment]
Cool, thanks! 👍
