### ISSUE TITLE
EventSub mock server - reconnect test - no reconnect message

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/twitch-cli#182]
In testing

> twitch event start-websocket-server -r 30

I connect a client

When the "time comes"
- The client didn't recieve a reconnect payload.
- The client didn't get force disconnect after the reconnect time (and a bit) occurs (so with -r 30 seconds should trigger the recon payload, and another 15 seconds should then disconnect clients/shutdown
- The client is still recieving keepalives _forever_

**Comment by Xemdo** [comment]
Should be fixed in next release
![image](https://user-images.githubusercontent.com/11840265/197084035-f9c85cc2-a8a8-4ff8-baaa-a972cfe5f45c.png)
