### ISSUE TITLE
Add trigger support for EventSub stream.online and stream.offline events

### ISSUE THREAD

**Issue by aydrian** [twitchdev/twitch-cli#19]
It would be great to have support for triggering stream.online and stream.offline events so I can easily test my applications using EventSub.

**Comment by lleadbet** [comment]
Definitely on the shortlist- goal is to get complete parity short-term, but will try and get this prioritized. :)

**Comment by aydrian** [comment]
I appreciate it. Would definitely go back and update some blog posts. Would have attempted to add it but Go is not a language I know well enough.
