### ISSUE TITLE
Mock for tags returns an array of tags instead of a string/string map

### ISSUE THREAD

**Issue by JMTK** [twitchdev/twitch-cli#198]
Observed:
![image](https://user-images.githubusercontent.com/877114/202769831-7abac76e-a222-407f-b9fb-ebf7f67f2e22.png)

Expected:
![image](https://user-images.githubusercontent.com/877114/202769838-20ade1a2-ee4b-4457-a351-582b056db965.png)

**Comment by Xemdo** [comment]
Appears to be on both /tags/streams and /streams/tags mock API calls.

**Comment by Xemdo** [comment]
Moved to the larger-scale issue #207
