### ISSUE TITLE
Pretty Print disables when used

### ISSUE THREAD

**Issue by erkrnt** [twitchdev/twitch-cli#2]
## Expected Behavior

When using the `--pretty-print` argument - it should stay enabled and output something like this:

```
{
  "data": [
    {
      "broadcaster_type": "affiliate",
      "created_at": "2018-10-01T15:26:44.113951Z",
      "description": "The Alt-F4 Stream is an idea long time friends AT0TA and Blackglasses had of being able to game/stream together miles apart. We are real life friends that met long ago in a little town in Florida and kept our friendship over the years through video games. Find out more about us below!",
      "display_name": "TheAltF4Stream",
     ....
    }
  ]
}
```

## Actual Behavior

It appears to be disabling the flag when used instead of keeping it enabled rendering non-pretty output:

```
{"data":[{"id":"264030156","login":"thealtf4stream","display_name":"TheAltF4Stream","type":"","broadcaster_type":"affiliate","description":"The Alt-F4 Stream is an idea long time friends AT0TA and Blackglasses had of being able to game/stream together miles apart. We are real life friends that met long ago in a little town in Florida and kept our friendship over the years through video games. Find out more about us below!","profile_image_url":"https://static-cdn.jtvnw.net/jtv_user_pictures/ffedad62-cc6e-497f-8eef-61e7fec4c9b4-profile_image-300x300.png","offline_image_url":"https://static-cdn.jtvnw.net/jtv_user_pictures/ce008d9e-a92f-4781-a2d0-4bba41061812-channel_offline_image-1920x1080.png","view_count":95898,"created_at":"2018-10-01T15:26:44.113951Z"}]}
```

## Steps to Reproduce the Problem

1. Use the following command as an example and make sure `--pretty-print` is included.

```
twitch-cli api --pretty-print get users -q login=thealtf4stream
```

2. Should return a non-pretty output of your query.

## Specifications

- Version: Beta Version 0.1.0
- Platform: Linux

**Comment by lleadbet** [comment]
Hi there! 

You hit the nail on the head. It's a poorly named flag, so I may just need to rename it, but it's defaulted on and using it toggles it off. 

I'll dig into this and see the better solve here.

**Comment by omniboy** [comment]
I don't seem to understand the issue in the code. The boolean is getting inverted and that is accompanied with this comment:
`// default here is false to enable -p commands to toggle off without explicitly defining -p=false as -p false will not work. The below commands invert the bool to pass the true default`.

I've been running some tests and everything seems to be working just fine without the invert. Let me show you. For debugging purposes the command now also outputs the `print-pretty` condition.

No pretty print (`-p` and `--pretty-print` absent)
![grafik](https://user-images.githubusercontent.com/64563583/102651102-39631400-416c-11eb-980c-d7aa74718816.png)

Pretty print (`-p` specified, `--pretty-print` absent)
![grafik](https://user-images.githubusercontent.com/64563583/102651176-5f88b400-416c-11eb-9fe3-74ac7bf35090.png)

Pretty print (`-p` absent, `--pretty-print` specified)
![grafik](https://user-images.githubusercontent.com/64563583/102651213-73341a80-416c-11eb-9a74-31f57373f8f5.png)

Pretty print (`-p` and `--pretty-print` specified)
![grafik](https://user-images.githubusercontent.com/64563583/102651251-8515bd80-416c-11eb-9d3f-b7e42ac71e88.png)

I'm missing some intel. Is pretty print supposed to be enabled by default and you have to explicitly specify a flag to disable pretty print?

**Comment by omniboy** [comment]
All it boils down to is to rename the `pretty-print` flag to `unformatted`. 😃

**Comment by lleadbet** [comment]
Followup, this has a fix merged but isn't in a release just yet. I'll make sure that I followup once we cut a release.
