### ISSUE TITLE
[Feature Request] Add EventSub webhook revocation

### ISSUE THREAD

**Issue by Dkamps18** [twitchdev/twitch-cli#203]
Somehow the revocation message type is missing. Would be nice if we can test the handling of those too!
https://dev.twitch.tv/docs/eventsub/handling-webhook-events#revoking-your-subscription

**Comment by Xemdo** [comment]
Added in #169 as --subscription-status flag on `twitch event trigger`.
However I'm leaving this open as an improvement request, since it should be moved to its own command, similar to `twitch event verify`

**Comment by Xemdo** [comment]
Debated over this when implementing #217 and decided the current system works best. Given the need to send over multiple transports (webhook, websocket) it wouldn't fit well. May re-evaluate in the future.
