### ISSUE TITLE
[Feature Request] missed scope for authorize

### ISSUE THREAD

**Issue by alkboda** [twitchdev/twitch-cli#238]
### Tell us about your feature request

I can't get scope "moderator:read:chatters" through authorize endpoint.
But it is required for chat/chatters method (https://github.com/twitchdev/twitch-cli/blob/65b3af7a4c50c4f97adc17496690aef45ab2e7c2/internal/mock_api/endpoints/chat/chatters.go#LL24C5-L24C5)

### Disclaimer

- [X] I agree

**Comment by Xemdo** [comment]
Will be fixed in version 1.1.20
