### ISSUE TITLE
[Bug] Incorrect Return Value for Twitch CLI Testing Channel.Prediction.Lock

### ISSUE THREAD

**Issue by MrSniFo** [twitchdev/twitch-cli#241]
### What is the problem?

I've encountered a bug while using the Twitch CLI. When using the twitch event trigger channel.prediction.lock --transport=websocket command, the return value for the field "channel_points_won" is an integer, contrary to the documentation which states it should be null.

According to the documentation, the field "channel_points_won" should always be null for Prediction progress and Prediction lock events. It should only be 0 if the outcome did not win or if the Prediction was canceled with Channel Points refunded.

I believe this inconsistency between the expected behavior described in the documentation and the actual behavior of the Twitch CLI command is a bug. I kindly request your attention to this matter and a resolution to ensure the return value aligns with the documented behavior.

Please let me know if you require any additional information or if there's anything I can do to assist in resolving this issue promptly.

### Operating System

windows 10

### Architecture Version (x86, x64, arm, etc)

x64

### Steps to reproduce

1. Open the Twitch CLI.
2. Execute the command: twitch event trigger channel.prediction.lock --transport=websocket.

Expected result:
According to the documentation, the return value for the "channel_points_won" field should be null in the event payload for Prediction progress and Prediction lock.

Actual result:
Instead of returning null, the "channel_points_won" field is returning an integer value.

### Relevant log output

```shell
✔ Forwarded for use in mock EventSub WebSocket server
{"subscription":{"id":"7026093e-c640-02d2-9a00-4d184a72767c","status":"enabled","type":"channel.prediction.lock","version":"1","condition":{"broadcaster_user_id":"24703267"},"transport":{"method":"websocket","session_id":"WebSocket-Server-Will-Set"},"created_at":"2023-06-18T19:54:04.4393126Z","cost":0},"event":{"broadcaster_user_id":"24703267","broadcaster_user_login":"testBroadcaster","broadcaster_user_name":"testBroadcaster","id":"3957341a-fda4-2dbb-0bd9-534eb63c093a","locked_at":"2023-06-18T20:04:04.4393126Z","outcomes":[{"channel_points":18129,"color":"blue","id":"65a1851b-974d-ab92-d1c8-ddd2ea4ffc58","title":"yes","top_predictors":[{"channel_points_used":8724,"channel_points_won":17448,"user_id":"24721661","user_login":"testLogin","user_name":"testLogin"},{"channel_points_used":9405,"channel_points_won":18810,"user_id":"54114402","user_login":"testLogin","user_name":"testLogin"}],"users":2},{"channel_points":7841,"color":"pink","id":"1ed6ac9b-020a-3cad-cd46-ee73e404a949","title":"no","top_predictors":[{"channel_points_used":6016,"channel_points_won":0,"user_id":"54821927","user_login":"testLogin","user_name":"testLogin"},{"channel_points_used":1825,"channel_points_won":0,"user_id":"3875571","user_login":"testLogin","user_name":"testLogin"}],"users":2}],"started_at":"2023-06-18T19:54:04.4393126Z","title":"Will the developer finish this program?"}}
```

**Comment by Emilgardis** [comment]
this is the problematic code

https://github.com/twitchdev/twitch-cli/blob/74cca29b8c827e3bdbbf507663245ad8d35ff7eb/internal/events/types/prediction/prediction.go#L75-L80

should not be set on lock and progress
