### ISSUE TITLE
[Bug] DB Upgrade Error - duplicate column name: status

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/twitch-cli#258]
### What is the problem?

After upgrading to latest and testing a trigger for the first time in a while

Solved after deleting the DB file. After I guess where it was

### Operating System

mac

### Architecture Version (x86, x64, arm, etc)

intel

### Steps to reproduce

    $ twitch event trigger channel.follow -F https://localhost:8080/ --version 2
    DB Upgrade Error - duplicate column name: status
    Exiting program. Please report this bug, and delete your Twitch CLI db file to regenerate it.

**Comment by Xemdo** [comment]
Can't seem to reproduce,. What version were you upgrading from? 1.1.19?

As for the vague db file location, I'll add the location of it in the message.

**Comment by BarryCarlyon** [comment]
I have no idea off hand :-D

I didn't think to keep the db file.
So it might be a weird from _it's been a REAL long time since I did a trigger_

**Comment by Xemdo** [comment]
Tried as far back as 1.1.4 and couldn't reproduce. Not sure where the error came from.

**Comment by aydrian** [comment]
I just received this error twice. I was executing the following commands:

```shell
twitch event trigger subscribe -F http://localhost:3000/resources/twitch/eventsub/itsaydrian \
  -s <SECRET>  \
  -f 114823831 \
  -i "644b10b6-92ac-4f59-8baa-21c3b3cae5cb"
```

```shell
twitch event trigger raid -F http://localhost:3000/resources/twitch/eventsub/itsaydrian \
  -s <SECRET> \
  -f 114823831 \
  -i "644b10b6-92ac-4f59-8baa-21c3b3cae5cb"
```
I don't know where the db file is so I haven't deleted anything.

**Comment by aydrian** [comment]
I deleted the `eventCache.db` in ~/.twitch-cli and it started working.
