### ISSUE TITLE
[Feature Request] EventSub testing Force IPv4

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/twitch-cli#259]
### Tell us about your feature request

At time of writing Twitch only speaks IPv4

But the CLI will use _whatever works_ on the computer and the target server.

The EventSub tester should _force_ making a connection over IPv4

### Disclaimer

- [X] I agree

**Comment by Xemdo** [comment]
Is this for EventSub WebSocket's specifically? Or EventSub Webhook forwarding as well?

**Comment by BarryCarlyon** [comment]
Context/Source of the issue is https://discuss.dev.twitch.tv/t/webhook-validation-failed-without-any-request/46810/

So this effects Webhooks for callback valiation/checking it works.

For websockets I don't think this matters.
