### ISSUE TITLE
verify-subscription sends wrong value for Twitch-Eventsub-Message-Type header

### ISSUE THREAD

**Issue by aydrian** [twitchdev/twitch-cli#26]
It looks like the new verify-subscription event is sending "notification" as the value for the Twitch-Eventsub-Message-Type header. It should be "webhook_callback_verification". I check this value in my route and respond with the challenge if it's "webhook_callback_verification". This is causing the CLI command to fail for my endpoint.

**Comment by lleadbet** [comment]
@aydrian - Have a fix coming and should be out sometime next week in the nightlies. 

Thanks for flagging this!

**Comment by lleadbet** [comment]
@aydrian - the fix should be out with tonight's Nightly, but I'll cut a proper release soon.

**Comment by aydrian** [comment]
Thank you. When is the next proper release?

**Comment by lleadbet** [comment]
I'll be cutting a release this afternoon so long as the two outstanding PRs are merged in; will let you know once that happens.

**Comment by lleadbet** [comment]
It's been cut. :) v0.3.3.
