### ISSUE TITLE
Validate token feature

### ISSUE THREAD

**Issue by Xemdo** [twitchdev/twitch-cli#271]
### Tell us about your feature request

Right now `twitch token` has the ability to revoke, such as:
```
twitch token --client-id CLIENT_ID --revoke OAUTH_TOKEN
```
In a similar fashion, we should have a way to validate tokens:
```
twitch token --validate OAUTH_TOKEN
```
This would return information similar to [Barry's Token Checker](https://barrycarlyon.github.io/twitch_misc/examples/token_checker/), which uses the [/oauth2/validate endpoint](https://dev.twitch.tv/docs/authentication/validate-tokens/).

### Disclaimer

- [X] I agree

**Comment by GStefanowich** [comment]
Is the CLI capable of doing `||`s with if a CLI parameter is present?

Could you theoretically do

```
twitch token --validate OAUTH_TOKEN --revoke
twitch token --validate --revoke OAUTH_TOKEN
```

without having to do

```
twitch token --validate OAUTH_TOKEN --revoke OAUTH_TOKEN
```

**Comment by Xemdo** [comment]
Ideally, you would validate or revoke. Doing both doesn't provide much since revoke requires a valid token, and will fail if the token is not valid.

**Comment by Xemdo** [comment]
Added in #277
