### ISSUE TITLE
[Bug] Using verify-subscription channel.follow requires version param

### ISSUE THREAD

**Issue by dynamitejustice** [twitchdev/twitch-cli#288]
### What is the problem?

When attempting to perform the command ` twitch event verify-subscription channel.follow` the reponse says that the version is invalid and requires 1,2.  This makes sense as when you attempt to just do a event trigger for follow I add `--version 2` at the end and it works fine.  I'm unable to add `--version 2` or even 1 anywhere within the call for it to specify the version needed and perform the verify-subscription action.  I have tried moving the `--version 2` param around in case it was an order of operations thing but no luck.

### Operating System

Windows 10

### Architecture Version (x86, x64, arm, etc)

x64

### Steps to reproduce

1. Perform the following command ` twitch event verify-subscription channel.follow -F https://[redacted]/callback -s [redacted] --version 2`
2. Note the response of `Invalid version given. Valid version(s): 1, 2
Use --version to specify`

**Comment by Xemdo** [comment]
Should be solved for `channel.follow` by #290 because it reduces it down to just one version, but that doesn't solve the underlying issue. I'll try to add in a fix before the next release to avoid future issues.
