### ISSUE TITLE
Simulate Keepalive Message Interruption [Feature Request] 

### ISSUE THREAD

**Issue by Robertsmania** [twitchdev/twitch-cli#291]
### Tell us about your feature request

For testing client logic to handle KeepAlive Messages it would be helpful to have an option with the CLI to suspend or interrupt the outgoing messages.

I'm not certain of the causes or conditions that could cause a real server in production to stop sending the messages, but from the documentation it sounds like the connection itself is still considered open (or at least has not received an explicit close).

Ideally, the option with the CLI would stop sending the Keepalive Messages to an existing client but not prohibit establishing new connections which would receive the messages as normal.  Perhaps specifying the SessionID to suspend?

### Disclaimer

- [X] I agree

**Comment by Xemdo** [comment]
This will be implemented two ways:

Toggling
`twitch event websocket keepalive --session=[Session ID]`

Specific setting
`twitch event websocket keepalive --session=[Session ID] --enabled=[true/false]`
