### ISSUE TITLE
Misspelled variable name

### ISSUE THREAD

**Issue by aaaaaa123456789** [twitchdev/twitch-cli#3]
This one's really minor, but I figured there's no reason to not report it. The word "parameters" is frequently misspelled as "paramaters" in a number of identifiers. Some quick grepping tells me this is found in `internal/api/api.go`, `internal/events/trigger_event.go`, `internal/events/retrigger_event.go` and `cmd/events.go`.

**Comment by lleadbet** [comment]
That's my bad, but will get in a PR shortly along with some other fixes. 

Thanks for the flag!

**Comment by lleadbet** [comment]
Followup, this has a fix merged but isn't in a release just yet. I'll make sure that I followup once we cut a release.
