### ISSUE TITLE
twitch-cli should use standard config directory

### ISSUE THREAD

**Issue by Toniob** [twitchdev/twitch-cli#33]
Hi,

Right now, twitch-cli is using $HOME/.twitch-cli directory as its default config path. It is kind of anoying, putting another directory in the home of the user.
At least under Linux, it should use the now quite common directory $HOME/.config/ with a subdir in it : $HOME/.config/twitch-cli/ .

What do you think ?

**Comment by lleadbet** [comment]
Definitely something we can consider, however this would be a larger breaking change- this is similar to the AWS CLI with the naming format, however.

**Comment by deefdragon** [comment]
Would it be reasonable to check `$HOME/.config/twitch-cli/` then `$HOME/.twitch-cli`, and if neither exists, create new configs at `$HOME/.config/twitch-cli/`?

**Comment by lleadbet** [comment]
I have a PR open for this and hoping to push this out with the next release.
