### ISSUE TITLE
Configure command doesn't accept valid client secret

### ISSUE THREAD

**Issue by FreddyOriginal** [twitchdev/twitch-cli#4]
## Issue

The current client secret validation only accepts secrets with a length of exactly 30 characters. However, my valid secret has 31.
It's worth mentioning that my application is one of the so-called old applications. Maybe those are (or were) able to generate secrets with variable length.

## Current workaround

Configure the CLI with a random 30 character secret and edit the resulting `.twitch-cli.env` file manually afterwards.

**Comment by lleadbet** [comment]
Thanks for the workaround- I thought I had addressed this, but must've slipped through the cracks. 

I'll get this done in an upcoming PR- should be trivial.

**Comment by lleadbet** [comment]
Followup, this has a fix merged but isn't in a release just yet. I'll make sure that I followup once we cut a release.
