### ISSUE TITLE
Release for macOS ARM

### ISSUE THREAD

**Issue by aydrian** [twitchdev/twitch-cli#52]
Would it be possible to also release this for the new M1 macs? I was able to install it using the Silicon version of Homebrew until 0.6.0. I see the formula is explicitly checking for Mac and Intel now.

**Comment by lleadbet** [comment]
We swapped to goreleaser which is precompiling binaries; let me see if we can compile for ARM now or if there's a way to allow for manually building on M1 macs for the interim.

**Comment by gurthyy** [comment]
Adding a note to this so I can be reminded of this, as I'm experiencing the same issue.

**Comment by lleadbet** [comment]
@aydrian / @gurthyy - Can either of you try running a reinstall for me? Try: 

```
brew install twitchdev/twitch/twitch-cli
```

And see if it builds for you.

**Comment by gurthyy** [comment]
I was able to successfully build and use! Appreciate it!

**Comment by aydrian** [comment]
Worked for me as well. Thanks!

**Comment by lleadbet** [comment]
Amazing, thank you both! I've got a PR to put in a more permanent fix since the current one is just a bandaid on the current tap, so let me know if you continue to see this in the future.
