### ISSUE TITLE
Schedule endpoints error

### ISSUE THREAD

**Issue by PalmettoBling** [twitchdev/twitch-cli#67]
Any call to the new Schedule endpoints returns: 
`Error unmarshalling body: json: cannot unmarshal object into Go struct field APIResponse.data of type []interface {}`

schedule icalendar endpoint returns:
`Error unmarshalling body: invalid character ‘B’ looking for beginning of value.`

Similar errors across all the /schedule endpoints.  

Error was present and consistent in 1.0 and 1.0.2 builds.

**Comment by lleadbet** [comment]
Is this for all endpoints? If so- I believe there's actually a fix already in the nightlies that resolves this; if not, please let me know a sample call and happy to dig further.

**Comment by PalmettoBling** [comment]
I haven't tested Create, Update, or Delete via CLI.  I'm unable to pull the ID of the segment from the GET to test.  
I'm still receiving the error from:
`twitch api get schedule -q broadcaster_id=foo`
`Error unmarshalling body: json: cannot unmarshal object into Go struct field APIResponse.data of type []interface {}`
Even with the -u unformatted flag.  

Might be able to work around test data this weekend to attempt the Create, Update, and Delete operations.

**Comment by lleadbet** [comment]
Got it. This seems to be tied to this specific version, but changes in the next release (which is being cut very shortly) will resolve this. I'll keep this open for now, but will close out with the next release.
