### ISSUE TITLE
New events related to channel subscription messages and gifts

### ISSUE THREAD

**Issue by cgbuen** [twitchdev/twitch-cli#68]
Will there be support for triggering the new events for Channel Subscription Gift and Channel Subscription Message, which were just moved out of public beta and into v1 this past month (June 11 and June 15 respectively)?

https://dev.twitch.tv/docs/change-log
https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelsubscriptiongift
https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelsubscriptionmessage

**Comment by lleadbet** [comment]
Hey there! I have plans to catch up the CLI starting shortly, so stay tuned.

**Comment by lleadbet** [comment]
As a followup, this will be released here in an hour or so once I get this PR merged. :)
