### ISSUE TITLE
Nested arrays in API responses

### ISSUE THREAD

**Issue by zneix** [twitchdev/twitch-cli#74]
When performing any API request, `data` array in returned body contains unnecessary array inside with the content, which I believe shouldn't be a case.
Expected behavior is to have the response looking as close to the official API response, with just one array of objects.

Example (tcurl is an alias for `curl <headers with my credentials> $@`):
![forsen in the background](https://cdn.zneix.eu/VXYQmVO.png)

I'd want the `data` array in response of twitch-cli, to look just like `data` array in the API call in the example shown above.

**Comment by lleadbet** [comment]
What version are you running on?

**Comment by zneix** [comment]
> What version are you running on?

I use AUR package that I package myself, `twitch-cli-git r245.daa4458-1` - commit daa4458 (latest master)

**Comment by lleadbet** [comment]
Got it; let me get a fix pushed into main.
