### ISSUE TITLE
mock-api: event_type and event_timestamp is swapped

### ISSUE THREAD

**Issue by Emilgardis** [twitchdev/twitch-cli#83]
I tried to fix this myself, but having trouble understanding how the sql is used and my knowledge of go is minimal.

The issue is that `mock/moderation/banned/events` and `mock/moderation/moderators/events` endpoints return wrong data

![image](https://user-images.githubusercontent.com/1502855/127926804-27b998c1-7ebc-4671-bf6b-d9a5d7afebf4.png)
![image](https://user-images.githubusercontent.com/1502855/127926828-f7a16366-28dc-411a-9a98-96db2ed18c13.png)

**Comment by Emilgardis** [comment]
Specifically, my issue with understanding the sql is about the migration, seems there is a migration that should be ran, but currently it's on version 2. https://github.com/twitchdev/twitch-cli/blob/9370e1a999ea95699e0af69a7689f84edc98f350/internal/database/init.go#L13

**Comment by lleadbet** [comment]
Sounds like there are two bugs- the first is that the version hasn’t been updated properly- that’s relatively simple. 

For reference; the migration script runs to make the stored version of the DB equal to the migration number. The current version embedded is used on first creation as the creation script usually includes any migrated tables/cols. 

The second bug is the swapping of the values- I’ll dig into that next week.
