### ISSUE TITLE
Extend Configure for EventSub Defaults

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/twitch-cli#96]
For a user testing eventsub they would have to `-F` and `-s` _every command_

It would be useful for a developer to define a default, potentially via the `configure` command

So when doing a lot of eventsub testing, a developer doesn't have to specify `-F` and `-s` _everytime_ since it's gonna be _easy_ to fatfinger the `-s` and/or copy paste all the time.

Also nicer for people on shell only to test.

**Comment by lleadbet** [comment]
Good callout. Definitely something we can look to add in the future.
